WebApplication2/Models/Category.cs
namespace WebApplication2.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int DisplayOrder { get; set; }
    }
}

WebApplication2/Models/ErrorViewModel.cs
namespace WebApplication2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication2/Models/Friend.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models
{
    public class Friend
    {
        [ScaffoldColumn(true)]
        [Required]
        [Display(Name ="Friend ID")]

        public int FriendID { get; set; }
        [Display(Name = "Name")]
        [Required(ErrorMessage = "Friend Name Empty Not Allowed.")]
        public string FriendName { get; set; }
        [Display(Name = "Address")]
        [MaxLength(25)]
        public string Place { get; set; }
    }
}

WebApplication2/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;
using WebApplication2.Data;

namespace WebApplication2.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }
        public ActionResult<string> Index()
        {
            return View();
        }
        public ActionResult<string> Edit()
        {
            return View("Index");
        }
        //public ActionResult<string> Create(int id, string test)
        //{
        //    //return id;
        //    return Json(new { name = "Biw", Age = 30 });
        //    //return View();
        //}
        public ActionResult<IEnumerable<Category>> GetAll() //IEnumerable => [list or array]
        {
            var categories = _context.Categories.ToList(); //table name
            return categories;
        }

        public ActionResult<Category> Get(int id)
        {
            var category = _context.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return category;
        }

        [HttpPost]
        public ActionResult Create(Category category)
        {
            _context.Categories.Add(category);
            _context.SaveChanges();
            return Ok(category);
        }
        [HttpPost]
        public ActionResult Update(int id, Category category)
        {
            var PendingUpdatecategory = _context.Categories.Find(id);
            PendingUpdatecategory.DisplayOrder = category.DisplayOrder;
            _context.Categories.Update(PendingUpdatecategory);
            _context.SaveChanges();
            return Ok(category);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var PendingDeletecategory = _context.Categories.Find(id);
            if (PendingDeletecategory == null)
            {
                return NotFound();
            }
            _context.Categories.Remove(PendingDeletecategory);
            _context.SaveChanges();
            return Ok("Delete Success");
        }
    }
}

WebApplication2/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;
using WebApplication2.Data;

namespace WebApplication2.Controllers
{
    public class FriendController : Controller
    {
        public IActionResult Index()
        {
            var data = _context.Friends.OrderBy(f=>f.FriendName).ToList();

            return View(data);
        }
        public IActionResult New()
        {
            return View();
        }
        public IActionResult Update(int id)
        {
            var fid = _context.Friends.Find(id);
            if (fid == null)
            {
                return NotFound();
            }
            return View(fid);
        }
        private readonly ApplicationDbContext _context;
        public FriendController(ApplicationDbContext context) // public classs ... => public ... 
        {
            _context = context;
        }

        public ActionResult<IEnumerable<Friend>> Get() //IEnumerable => [list or array]
        {
            var fs = _context.Friends.ToList();
            return fs;
        }

        [HttpPost]
        public ActionResult New(Friend friend)
        {
            //if (ModelState.IsValid)
            //{
            //    _context.Friends.Add(newFriend);
            //    _context.SaveChanges();
            //    return Ok(newFriend);
            //}
            //else
            //{
            //    return BadRequest();
            //}
            if (ModelState.IsValid)
            {
                var existing = _context.Friends.Find(friend.FriendID);
                if (existing != null)
                {
                    return BadRequest();
                }

                _context.Friends.Add(friend);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }

        //[HttpPost]
        //public ActionResult Update(int id, Friend selectFriend)
        //{
        //    var PendingUpdatefriend = _context.Friends.Find(id);
        //    PendingUpdatefriend.Place = selectFriend.Place;
        //    _context.Friends.Update(PendingUpdatefriend);
        //    _context.SaveChanges();
        //    return Ok(selectFriend);
        //}
        [HttpPost]
        public ActionResult Update(Friend friend)
        {

            if (ModelState.IsValid)
            {

                _context.Friends.Update(friend);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var PendingDeleteFriend = _context.Friends.Find(id);
            if (PendingDeleteFriend == null)
            {
                return NotFound();
            }
            _context.Friends.Remove(PendingDeleteFriend);
            _context.SaveChanges();
            //return Ok("Delete Success");
            return Json(new { Success = true ,message=""});
        }
    }
}

WebApplication2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var fullname = ("ชฎิล", "ชัยพรพิศุทธิ์");
            ViewData["myname"] = fullname.Item1 + " " + fullname.Item2; 
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication2/Views/Category/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <h1>123</h1>
    <h2>@ViewData["myname"]</h2>
}

WebApplication2/Views/Friend/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    
}
@*@model Friend
<div class="row">
        <div class="col-md-4"></div>
    <div class="col-md-4">
    <form method="post" asp-action="New">
        <div class="text-danger"></div>
        <div class="form-group">
        </div>
        <div class="form-group">
        <label asp-for="@Model.FriendID" class="control-label"></label>
        <input type="text" class="form-control" readonly />
        <span asp-validation-for="@Model.FriendID" class="text-danger"></span>
        <label asp-for="@Model.FriendName" class="control-label"></label>
        <input type="text" class="form-control" />
        <span asp-validation-for="@Model.FriendName" class="text-danger"></span>
        <label asp-for="@Model.Place" class="control-label"></label>
        <input type="text" class="form-control" />
        <span asp-validation-for="@Model.Place" class="text-danger"></span>
        <div class="btnGroup position-relative">
        <button type="submit" class="btn btn-success">Add</button>
        <a asp-action="Index" class="btn btn-warning">Back</a>
        @*<button type="reset" class="btn btn-danger">Reset</button
        </div>
        </div>
    </form>
    </div>
    </div>*@
@model Friend

<div>
    <h1>Edit Friend</h1>
    <form method="post" asp-action="Edit">
        
        <div>

            <label asp-for="@Model.FriendName" class="form-label"></label>
            <input asp-for="@Model.FriendName" class="form-control">
            <span asp-validation-for="@Model.FriendName" class="text-danger"></span>
        </div>
        <div>

            <label asp-for="@Model.Place" class="form-label"></label>
            <input asp-for="@Model.Place" class="form-control">
            <span asp-validation-for="@Model.Place" class="text-danger"></span>
        </div>

        <div class="mt-5">
            <button type="submit" class="btn btn-info">Save</button>
            <a asp-action="Index" class="btn btn-danger">Back</a>
        </div>
    </form>
</div>

WebApplication2/Views/Friend/Index.cshtml
@*@model IEnumerable<WebApplication2.Models.Friend>*@
@model IEnumerable<Friend>
@{
    ViewData["Title"] = "All Friend";
}
<table class="table">
     <thead>
    <tr>
        <th scope="col">@Html.DisplayNameFor(model => model.FriendID)</th>
        <th scope="col">@Html.DisplayNameFor(model => model.FriendName)</th>
        <th scope="col">@Html.DisplayNameFor(model => model.Place)</th>
        @*<th scope="col">FriendID</th>*@
        @*<th scope="col">FriendName</th>
        <th scope="col">Place</th>*@
        <th scope="col">Do</th>

    </tr>
    </thead>
    <tbody>
@foreach (var friend in Model) {
    <tr>
    <td>@friend.FriendID</td>
    <td>@friend.FriendName</td>
    <td>@friend.Place</td>
    @*<td>
        <a asp-controller="friend" asp-action="Edit" asp-route-FriendID="@item.FriendID" class="btn btn-warning">Edit</a>
        <button type="reset" class="btn btn-danger">Delete</button>
    </td>*@
    <td>
        @*<a asp-action="Update" asp-route-friendId="@friend.FriendID" class="btn btn-warning">Edit</a>*@
        <a asp-action="Update" asp-route-id="@friend.FriendID" class="btn btn-warning">Edit</a>
        <a onclick="deleteFriend(@friend.FriendID);" class="btn btn-danger">Delete</a>
    </td>
    </tr>
}
</tbody>
</table>
@section Scripts {
    <script>
        function deleteFriend(friendId) {
            $.ajax({
                url: `/Friend/Delete/${friendId}`,
                method: 'Delete',
                success: function(data) { 
                    if (data.success) {
                        //alert("Deleted");
                        //var urlToRedirect = "@Url.Action("Index")";
                        location.reload();
                    }
                },
                error: function(err) { alert(err); }
            })
        }
    </script>
}

WebApplication2/Views/Friend/New.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add a Friend";
}
@model Friend
@*<div class="row">
        <div class="col-md-4"></div>
    <div class="col-md-4">
    <form method="post" asp-action="New">
        <div class="text-danger"></div>
        <div class="form-group">
        </div>
        <div class="form-group">
        <label asp-for="@Model.FriendID" class="control-label"></label>
        <input type="text" class="form-control" />
        <span asp-validation-for="@Model.FriendID" class="text-danger"></span>
        <label asp-for="@Model.FriendName" class="control-label"></label>
        <input type="text" class="form-control" />
        <span asp-validation-for="@Model.FriendName" class="text-danger"></span>
        <label asp-for="@Model.Place" class="control-label"></label>
        <input type="text" class="form-control" />
        <span asp-validation-for="@Model.Place" class="text-danger"></span>
        <div class="btnGroup position-relative">
        <button type="submit" class="btn btn-success">Add</button>
        <a asp-action="Index" class="btn btn-warning">Back</a>
        </div>
        </div>
    </form>
    </div>
    </div>*@



<div>
    <h1>New Friend</h1>
    <form method="post" asp-action="New">
        @*<div>

            <label asp-for="@Model.FriendID" class="form-label"></label>
            <input asp-for="@Model.FriendID" class="form-control">
            <span asp-validation-for="@Model.FriendID" class="text-danger"></span>
        </div>
        *@
        <div>

            <label asp-for="@Model.FriendName" class="form-label"></label>
            <input asp-for="@Model.FriendName" class="form-control">
            <span asp-validation-for="@Model.FriendName" class="text-danger"></span>
        </div>
        <div>

            <label asp-for="@Model.Place" class="form-label"></label>
            <input asp-for="@Model.Place" class="form-control">
            <span asp-validation-for="@Model.Place" class="text-danger"></span>
        </div>

        <div class="mt-5">
            <button type="submit" class="btn btn-info">Create</button>
            <a asp-action="Index" class="btn btn-danger">Back</a>
        </div>
    </form>
</div>

WebApplication2/Views/Friend/Update.cshtml
@model Friend
@{
    ViewData["Title"] = "Update Friend Info";
}
<div>
    <h1>Edit Friend</h1>
    <form method="post" asp-action="Update">
        <input asp-for="FriendID" class="form-control" hidden>
        <div>

            <label asp-for="FriendID" class="form-label"></label>
            <input asp-for="FriendID" class="form-control" disabled>
            <span asp-validation-for="FriendID" class="text-danger"></span>
        </div>


        <div>
            <label asp-for="FriendName" class="form-label"></label>
            <input asp-for="FriendName" class="form-control">
            <span asp-validation-for="FriendName" class="text-danger"></span>
        </div>
        <div>

            <label asp-for="Place" class="form-label"></label>
            <input asp-for="Place" class="form-control">
            <span asp-validation-for="Place" class="text-danger"></span>
        </div>

        <div class="mt-5">
            <button type="submit" class="btn btn-info">Save</button>
            <a asp-action="Index" class="btn btn-danger">Back</a>
        </div>
    </form>
</div>

WebApplication2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h2>@ViewData["myname"]</h2>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Friend</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="New">New Friend</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2565 - WebApplication2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>